#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
kNN algorithm and Naive Bayes implementations
by Ziyang Zeng(zz2960)
Spring 2022
"""

import pandas as pd
import argparse


def main():
    parser = argparse.ArgumentParser(
        description="kNN algorithm and Naive Bayes implementations.")
    parser.add_argument(
        "--train", help="the training csv data file", type=str, required=True)
    parser.add_argument(
        "--test", help="the testing csv data file", type=str, required=True)
    parser.add_argument(
        "-k", help="if > 0 indicates to use kNN and also the value of K (if 0, do Naive Bayes')", type=int, required=False,
        default=0)
    parser.add_argument(
        "-c", help="if > 0 indicates the Laplacian correction to use (0 means don't use one)", type=float, required=False, default=0)
    parser.add_argument(
        "-v", "--verbose", help="outputs each predicted vs actual label", action="store_true", default=False, required=False)
    parser.parse_args()
    pass


if __name__ == '__main__':
    main()
